//Define constants for project-wide usage

export const rarityLabels = [
	{ label: 'Common', value: 'Common' },
	{ label: 'Rare', value: 'Rare' },
	{ label: 'Promo', value: 'Promo' },
	{ label: 'LEGEND', value: 'LEGEND' },
	{ label: 'Rare ACE', value: 'Rare ACE' },
	{ label: 'Rare BREAK', value: 'Rare BREAK' },
	{ label: 'Rare Holo', value: 'Rare Holo' },
	{ label: 'Rare Holo EX', value: 'Rare Holo EX' },
	{ label: 'Rare Holo GX', value: 'Rare Holo GX' },
	{ label: 'Rare Holo LV.X', value: 'Rare Holo LV.X' },
	{ label: 'Rare Holo Star', value: 'Rare Holo Star' },
	{ label: 'Rare Holo V', value: 'Rare Holo V' },
	{ label: 'Rare Holo VMAX', value: 'Rare Holo VMAX' },
	{ label: 'Rare Prime', value: 'Rare Prime' },
	{ label: 'Rare Rainbow', value: 'Rare Rainbow' },
	{ label: 'Rare Secret', value: 'Rare Secret' },
	{ label: 'Rare Shining', value: 'Rare Shining' },
	{ label: 'Rare Shiny', value: 'Rare Shiny' },
	{ label: 'Rare Shiny GX', value: 'Rare Shiny GX' },
	{ label: 'Rare Ultra', value: 'Rare Ultra' },
  ];

export const typeLabels = [
  	{ label: 'Fire', value: 'Fire' },
	{ label: 'Water', value: 'Water' },
	{ label: 'Grass', value: 'Grass' },
	{ label: 'Darkness', value: 'Darkness' },
	{ label: 'Dragon', value: 'Dragon' },
	{ label: 'Lightning', value: 'Lightning' },
	{ label: 'Fairy', value: 'Fairy' },
	{ label: 'Fighting', value: 'Fighting' },
	{ label: 'Colorless', value: 'Colorless' },
	{ label: 'Psychic', value: 'Psychic' },
	{ label: 'Metal', value: 'Metal' },
]; 

export const hpLabels = [
	{ label: '10', value: '10' },
	{ label: '20', value: '20' },
	{ label: '30', value: '30' },
	{ label: '40', value: '40' },
	{ label: '50', value: '50' },
	{ label: '60', value: '60' },
	{ label: '70', value: '70' },
	{ label: '80', value: '80' },
	{ label: '90', value: '90' },
	{ label: '100', value: '100' },
	{ label: '110', value: '110' },
	{ label: '120', value: '120' },
	{ label: '130', value: '130' },
	{ label: '140', value: '140' },
	{ label: '150', value: '150' },
	{ label: '160', value: '160' },
	{ label: '170', value: '170' },
	{ label: '180', value: '180' },
	{ label: '190', value: '190' },
	{ label: '200', value: '200' },
	{ label: '210', value: '210' },
	{ label: '220', value: '220' },
	{ label: '230', value: '230' },
	{ label: '240', value: '240' },
	{ label: '250', value: '250' },
	{ label: '260', value: '260' },
	{ label: '270', value: '270' },
	{ label: '280', value: '280' },
	{ label: '290', value: '290' },
	{ label: '300', value: '300' },
	{ label: '310', value: '310' },
	{ label: '320', value: '320' },
	{ label: '330', value: '330' },
	{ label: '340', value: '340' },
];

export const seriesLabels = [
	{ label: 'Base', value: 'Base' },
	{ label: 'Jungle', value: 'Jungle' },
	{ label: 'Wizards Black Star Promos', value: 'Wizards Black Star Promos' },
	{ label: 'Fossil', value: 'Fossil' },
	{ label: 'Base Set 2', value: 'Base Set 2' },
	{ label: 'Team Rocket', value: 'Team Rocket' },
	{ label: 'Gym Heroes', value: 'Gym Heroes' },
	{ label: 'Gym Challenge', value: 'Gym Challenge' },
	{ label: 'Neo Genesis', value: 'Neo Genesis' },
	{ label: 'Neo Discovery', value: 'Neo Discovery' },
	{ label: 'Southern Islands', value: 'Southern Islands' },
	{ label: 'Neo Revelation', value: 'Neo Revelation' },
	{ label: 'Neo Destiny', value: 'Neo Destiny' },
	{ label: 'Legendary Collection', value: 'Legendary Collection' },
	{ label: 'Expedition Base Set', value: 'Expedition Base Set' },
	{ label: 'Aquapolis', value: 'Aquapolis' },
	{ label: 'Skyridge', value: 'Skyridge' },
	{ label: 'Ruby & Sapphire', value: 'Ruby & Sapphire' },
	{ label: 'Sandstorm', value: 'Sandstorm' },
	{ label: 'Dragon', value: 'Dragon' },
	{ label: 'Nintendo Black Star Promos', value: 'Nintendo Black Star Promos' },
	{ label: 'Team Magma vs Team Aqua', value: 'Team Magma vs Team Aqua' },
	{ label: 'Hidden Legends', value: 'Hidden Legends' },
	{ label: 'FireRed & LeafGreen', value: 'FireRed & LeafGreen' },
	{ label: 'POP Series 1', value: 'POP Series 1' },
	{ label: 'Team Rocket Returns', value: 'Team Rocket Returns' },
	{ label: 'Deoxys', value: 'Deoxys' },
	{ label: 'Emerald', value: 'Emerald' },
	{ label: 'Unseen Forces', value: 'Unseen Forces' },
	{ label: 'POP Series 2', value: 'POP Series 2' },
	{ label: 'Delta Species', value: 'Delta Species' },
	{ label: 'Legend Maker', value: 'Legend Maker' },
	{ label: 'POP Series 3', value: 'POP Series 3' },
	{ label: 'Holon Phantoms', value: 'Holon Phantoms' },
	{ label: 'Crystal Guardians', value: 'Crystal Guardians' },
	{ label: 'POP Series 4', value: 'POP Series 4' },
	{ label: 'Dragon Frontiers', value: 'Dragon Frontiers' },
	{ label: 'POP Series 5', value: 'POP Series 5' },
	{ label: 'Power Keepers', value: 'Power Keepers' },
	{ label: 'Diamond & Pearl', value: 'Diamond & Pearl' },
	{ label: 'DP Black Star Promos', value: 'DP Black Star Promos' },
	{ label: 'Mysterious Treasures', value: 'Mysterious Treasures' },
	{ label: 'POP Series 6', value: 'POP Series 6' },
	{ label: 'Secret Wonders', value: 'Secret Wonders' },
	{ label: 'Great Encounters', value: 'Great Encounters' },
	{ label: 'POP Series 7', value: 'POP Series 7' },
	{ label: 'Majestic Dawn', value: 'Majestic Dawn' },
	{ label: 'Legends Awakened', value: 'Legends Awakened' },
	{ label: 'POP Series 8', value: 'POP Series 8' },
	{ label: 'Stormfront', value: 'Stormfront' },
	{ label: 'Platinum', value: 'Platinum' },
	{ label: 'POP Series 9', value: 'POP Series 9' },
	{ label: 'Rising Rivals', value: 'Rising Rivals' },
	{ label: 'Supreme Victors', value: 'Supreme Victors' },
	{ label: 'Arceus', value: 'Arceus' },
	{ label: 'Pokémon Rumble', value: 'Pokémon Rumble' },
	{ label: 'HeartGold & SoulSilver', value: 'HeartGold & SoulSilver' },
	{ label: 'HGSS Black Star Promos', value: 'HGSS Black Star Promos' },
	{ label: 'HS—Unleashed', value: 'HS—Unleashed' },
	{ label: 'HS—Undaunted', value: 'HS—Undaunted' },
	{ label: 'HS—Triumphant', value: 'HS—Triumphant' },
	{ label: 'Call of Legends', value: 'Call of Legends' },
	{ label: 'BW Black Star Promos', value: 'BW Black Star Promos' },
	{ label: 'Black & White', value: 'Black & White' },
	{ label: 'McDonald\'s Collection 2011', value: 'McDonald\'s Collection 2011' },
	{ label: 'Emerging Powers', value: 'Emerging Powers' },
	{ label: 'Noble Victories', value: 'Noble Victories' },
	{ label: 'Next Destinies', value: 'Next Destinies' },
	{ label: 'Dark Explorers', value: 'Dark Explorers' },
	{ label: 'McDonald\'s Collection 2012', value: 'McDonald\'s Collection 2012' },
	{ label: 'Dragons Exalted', value: 'Dragons Exalted' },
	{ label: 'Dragon Vault', value: 'Dragon Vault' },
	{ label: 'Boundaries Crossed', value: 'Boundaries Crossed' },
	{ label: 'Plasma Storm', value: 'Plasma Storm' },
	{ label: 'Plasma Freeze', value: 'Plasma Freeze' },
	{ label: 'Plasma Blast', value: 'Plasma Blast' },
	{ label: 'XY Black Star Promos', value: 'XY Black Star Promos' },
	{ label: 'Legendary Treasures', value: 'Legendary Treasures' },
	{ label: 'Kalos Starter Set', value: 'Kalos Starter Set' },
	{ label: 'XY', value: 'XY' },
	{ label: 'Flashfire', value: 'Flashfire' },
	{ label: 'Furious Fists', value: 'Furious Fists' },
	{ label: 'Phantom Forces', value: 'Phantom Forces' },
	{ label: 'Primal Clash', value: 'Primal Clash' },
	{ label: 'Double Crisis', value: 'Double Crisis' },
	{ label: 'Roaring Skies', value: 'Roaring Skies' },
	{ label: 'Ancient Origins', value: 'Ancient Origins' },
	{ label: 'BREAKthrough', value: 'BREAKthrough' },
	{ label: 'BREAKpoint', value: 'BREAKpoint' },
	{ label: 'Generations', value: 'Generations' },
	{ label: 'Fates Collide', value: 'Fates Collide' },
	{ label: 'Steam Siege', value: 'Steam Siege' },
	{ label: 'McDonald\'s Collection 2016', value: 'McDonald\'s Collection 2016' },
	{ label: 'Evolutions', value: 'Evolutions' },
	{ label: 'Sun & Moon', value: 'Sun & Moon' },
	{ label: 'SM Black Star Promos', value: 'SM Black Star Promos' },
	{ label: 'Guardians Rising', value: 'Guardians Rising' },
	{ label: 'Burning Shadows', value: 'Burning Shadows' },
	{ label: 'Shining Legends', value: 'Shining Legends' },
	{ label: 'Crimson Invasion', value: 'Crimson Invasion' },
	{ label: 'Ultra Prism', value: 'Ultra Prism' },
	{ label: 'Forbidden Light', value: 'Forbidden Light' },
	{ label: 'Celestial Storm', value: 'Celestial Storm' },
	{ label: 'Dragon Majesty', value: 'Dragon Majesty' },
	{ label: 'Lost Thunder', value: 'Lost Thunder' },
	{ label: 'Team Up', value: 'Team Up' },
	{ label: 'Detective Pikachu', value: 'Detective Pikachu' },
	{ label: 'Unbroken Bonds', value: 'Unbroken Bonds' },
	{ label: 'Unified Minds', value: 'Unified Minds' },
	{ label: 'Hidden Fates', value: 'Hidden Fates' },
	{ label: 'Hidden Fates Shiny Vault', value: 'Hidden Fates Shiny Vault' },
	{ label: 'McDonald\'s Collection 2019', value: 'McDonald\'s Collection 2019' },
	{ label: 'Cosmic Eclipse', value: 'Cosmic Eclipse' },
	{ label: 'SWSH Black Star Promos', value: 'SWSH Black Star Promos' },
	{ label: 'Sword & Shield', value: 'Sword & Shield' },
	{ label: 'Rebel Clash', value: 'Rebel Clash' },
	{ label: 'Darkness Ablaze', value: 'Darkness Ablaze' },
	{ label: 'Champion\'s Path', value: 'Champion\'s Path' },
	{ label: 'Vivid Voltage', value: 'Vivid Voltage' },
	{ label: 'Shining Fates', value: 'Shining Fates' },
	{ label: 'Shining Fates Shiny Vault', value: 'Shining Fates Shiny Vault' },
	{ label: 'Battle Styles', value: 'Battle Styles' },
	{ label: 'Chilling Reign', value: 'Chilling Reign' },
	{ label: 'Evolving Skies', value: 'Evolving Skies' },
	{ label: 'Celebrations', value: 'Celebrations' },
	{ label: 'Celebrations: Classic Collection', value: 'Celebrations: Classic Collection' },
	{ label: 'McDonald\'s Collection 2014', value: 'McDonald\'s Collection 2014' },
	{ label: 'McDonald\'s Collection 2015', value: 'McDonald\'s Collection 2015' },
	{ label: 'McDonald\'s Collection 2018', value: 'McDonald\'s Collection 2018' },
	{ label: 'McDonald\'s Collection 2017', value: 'McDonald\'s Collection 2017' },
	{ label: 'McDonald\'s Collection 2021', value: 'McDonald\'s Collection 2021' },
	{ label: 'Best of Game', value: 'Best of Game' },
	{ label: 'Fusion Strike', value: 'Fusion Strike' },
	{ label: 'Pokémon Futsal Collection', value: 'Pokémon Futsal Collection' },
	{ label: 'EX Trainer Kit Latias', value: 'EX Trainer Kit Latias' },
	{ label: 'EX Trainer Kit Latios', value: 'EX Trainer Kit Latios' },
	{ label: 'EX Trainer Kit 2 Plusle', value: 'EX Trainer Kit 2 Plusle' },
	{ label: 'EX Trainer Kit 2 Minun', value: 'EX Trainer Kit 2 Minun' },
	{ label: 'Brilliant Stars', value: 'Brilliant Stars' },
	{ label: 'Brilliant Stars Trainer Gallery', value: 'Brilliant Stars Trainer Gallery' },
	{ label: 'Astral Radiance', value: 'Astral Radiance' },
	{ label: 'Astral Radiance Trainer Gallery', value: 'Astral Radiance Trainer Gallery' },
	{ label: 'Pokémon GO', value: 'Pokémon GO' },
	{ label: 'Lost Origin', value: 'Lost Origin' },
	{ label: 'Lost Origin Trainer Gallery', value: 'Lost Origin Trainer Gallery' },
	{ label: 'Silver Tempest', value: 'Silver Tempest' },
	{ label: 'Silver Tempest Trainer Gallery', value: 'Silver Tempest Trainer Gallery' },
	{ label: 'McDonald\'s Collection 2022', value: 'McDonald\'s Collection 2022' },
	{ label: 'Crown Zenith', value: 'Crown Zenith' },
	{ label: 'Crown Zenith Galarian Gallery', value: 'Crown Zenith Galarian Gallery' },
	{ label: 'Scarlet & Violet', value: 'Scarlet & Violet' },
	{ label: 'Scarlet & Violet Black Star Promos', value: 'Scarlet & Violet Black Star Promos' },
	{ label: 'Paldea Evolved', value: 'Paldea Evolved' },
	{ label: 'Scarlet & Violet Energies', value: 'Scarlet & Violet Energies' },
	{ label: 'Obsidian Flames', value: 'Obsidian Flames' },
	{ label: '151', value: '151' },
	{ label: 'Paradox Rift', value: 'Paradox Rift' },
	{ label: 'Paldean Fates', value: 'Paldean Fates' },
	{ label: 'Temporal Forces', value: 'Temporal Forces' },
	{ label: 'Twilight Masquerade', value: 'Twilight Masquerade' },
	{ label: 'Shrouded Fable', value: 'Shrouded Fable' },
];